### ISSUE TITLE
Error 1025 - The data capture context has been disposed and can't be used anymore

### ISSUE THREAD

**Issue by veris-kamaraj** [Scandit/datacapture-react-native-samples#6]
i am facing  this issue in ios . i have two tabs home and scanner . when the app opens i was in home tab , when i switch to scanner tab the scandit sdk works fine . and when i switch to home sdk and then switch to scanner tab it says Error 1025 . i have used the https://github.com/Scandit/datacapture-react-native-samples/tree/master/IdCaptureSimpleSample. repo only . please help me on this
![Image_20240930_171851_166](https://github.com/user-attachments/assets/58537735-91d1-49f5-94c9-c2142b444ead)

**Comment by ScanditSupport** [comment]
Hi @veris-kamaraj,

My apologies for the issues you are experiencing.
Generally speaking the solution would depend on the exact implementation of the navigation.
As I can see - you have already [reached out to us directly](https://support.scandit.com/hc/en-us/requests/new), so we will review your implementation there.

**Comment by NitishCodingWorkx** [comment]
facing same issue,
has anyone found any solution ?

**Comment by ScanditSupport** [comment]
Hi @NitishCodingWorkx,

Error 1025 [[link](https://docs.scandit.com/data-capture-sdk/ios/core/api/context-status.html#disposed-context)] occurs when calling `.dispose()` [[link](https://docs.scandit.com/data-capture-sdk/ios/core/api/data-capture-context.html#method-scandit.datacapture.core.DataCaptureContext.Dispose)] on the `DataCaptureContext` instead of `.removeAllModes()` [[link](https://docs.scandit.com/data-capture-sdk/ios/core/api/data-capture-context.html#method-scandit.datacapture.core.DataCaptureContext.RemoveAllModes)], `.removeCurrentMode()` [[link](https://docs.scandit.com/data-capture-sdk/ios/core/api/data-capture-context.html#method-scandit.datacapture.core.DataCaptureContext.RemoveCurrentMode)], or `.removeMode(_:)` [[link](https://docs.scandit.com/data-capture-sdk/ios/core/api/data-capture-context.html#method-scandit.datacapture.core.DataCaptureContext.RemoveMode)]. 

If you're still having issues, please [contact support](https://support.scandit.com/hc/en-us/requests/new) with your Scandit SDK version and a copy of your scanning implementation attached.

**Comment by ibrust** [comment]
@ScanditSupport  calling dispose() just flat out throws in the react-native SDK 7.5.1, it claims the method is undefined.

**Comment by ScanditSupport** [comment]
Hi @ibrust,

Thanks for sharing your current Scandit SDK version. Can you please specify if you're using Android or iOS and share an example project by [contacting support](https://support.scandit.com/hc/en-us/requests/new)?

Best regards,
Scandit Support

**Comment by ibrust** [comment]
You're not facebook, you don't have 400 open issues, you have zero. It's
not my job to debug this for you - that's why we pay for this service, so
that you can do this.

**Comment by ScanditSupport** [comment]
Hi @ibrust, 

Thank you for sharing your thoughts. We hear your frustration and really want to make sure you get the support you need.

GitHub issues aren’t the best place for us to resolve individual cases. Our support team has the right tools to investigate and solve problems directly, and moving the conversation there also ensures your request is properly tracked and followed up until it’s resolved. If you reach out to us by [submitting a support ticket](https://support.scandit.com/hc/en-us/requests/new), we’ll be able to look into this right away and provide a more personalized resolution.

We truly appreciate your patience, and we’ll do our best to get this sorted quickly once you contact support.
